@startuml
title Warm House Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the smart home devices")
Person(staff, "Staff", "Adding new devices and their types")

System(SmartHome, "Smart Home", "Smart Home control system")


System_Ext(device, "User's devices", "Devices supporting predefined APIs")
System_Ext(payment,"Payment System", "Payment processing")


Rel(user, SmartHome, "Add/Control devices. Watch telemetry.")
Rel(staff, SmartHome, "Manage available device types and models")
Rel(SmartHome, device, "Controls Devices")
Rel(SmartHome, payment, "Sends payment data")
@enduml