@startuml
title Warm House Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the Warm House system")
Person(staff, "Staff", "Connecting new devices")

System(WarmHouse, "Warm House", "Warming control system")


System_Ext(device, "User's devices", "Devices supporting predefined APIs")

Rel(user, WarmHouse, "Turn on/off warming. Watch temperature.")
Rel(staff, WarmHouse, "Connect new warming devices")

Rel(WarmHouse, device, "Controls Devices")


@enduml